-- THIS IS HOW YOU WRITE COMMENT IN SQL
-- SINGLE LINE COMMENT LOOK LIKE THIS
/*
 THIS IS HOW WE WRITE MULTI LINE COMMENT
 */
-- * MEANS ALL! ; AT THE END - IS MANDATORY

SELECT * FROM REGIONS ;
SELECT * FROM COUNTRIES ;
SELECT * FROM LOCATIONS ;
SELECT * FROM DEPARTMENTS ;
SELECT * FROM JOB_HISTORY ;
SELECT * FROM EMPLOYEES ;
SELECT * FROM JOBS;

-- RESTRICTING COLUMNS IN THE RESULT
SELECT FIRST_NAME FROM EMPLOYEES;


--MORE THAN ONE COLUMN CAN BE SPECIFIED SEPARATED BY COMMA,
SELECT FIRST_NAME, LAST_NAME, EMAIL FROM EMPLOYEES;


--logical and

SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE FIRST_NAME='David' AND SALARY=4800;

--Display the Employee FIRST_NAME,LAST_NAME,SALARY
--for the employee with SALARY 4800 OR FIRST_NAME David
--Logical OR
SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE FIRST_NAME='David' OR SALARY=4800;

--Display the employees that make more than 500 and less that 12000
SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY>5000 AND SALARY<12000;

--Display the employees that have JOB_ID of
--AD_VP
--AD_ASST
--FI_ACCOUNT
--AC_ACCOUNT

SELECT * FROM EMPLOYEES
WHERE JOB_ID='AD_VP' OR JOB_ID='AD_ASST'OR JOB_ID='FI_ACCOUNT'
OR JOB_ID='AC_ACCOUNT';



